export const TIME = {
  MILLISECONDS_IN_SECOND: 1000,
  MILLISECONDS_IN_MINUTE: 60000,
  MILLISECONDS_IN_HOUR: 3600000,
  SECONDS_IN_MINUTE: 60,
  MINUTES_IN_HOUR: 60,
} as const;

export const TIMER_CONSTANTS = {
  MIN_MINUTES: 1,
  MAX_MINUTES: 60,
  DEFAULT_COUNTDOWN: 3000,
  MIN_COUNTDOWN: 0,
  MAX_COUNTDOWN: 10000,
  UPDATE_INTERVAL: 10,
  COUNTDOWN_INTERVAL: 1000,
  EMOM_WARNING_TIME: 50000,
  EMOM_DANGER_TIME: 55000,
  START_SOUND_THRESHOLD: 100,
} as const;

export const STORAGE_KEYS = {
  LAST_MODE: "lastMode",
  THEME: "theme",
  COUNTDOWN_DURATION: "countdownDuration",
} as const;

export const SOUNDS = {
  COUNTDOWN: "countdown",
  GO: "go",
  ROUND: "round",
  FINISH: "finish",
} as const;
